require_relative '../core/handlers/system_handler'
require_relative '../core/handlers/validation_handler'
require_relative '../core/handlers/provider_handler'
require_relative '../core/handlers/provisioner_handler'

SystemHandler.clear_screen
ValidationHandler.validate

Vagrant.configure('2') do |config|
  ProviderHandler.configure_box_and_ssh(config)

  config.vm.define Config.vm_name do |machine|
    ProviderHandler.configure_network(machine)
    machine.hostmanager.aliases = DemoStructure.additional_urls
  end

  config.vm.provider Provider.value do |machine|
    ProviderHandler.customize_vm(machine)
  end

  ProviderHandler.copy_items(config)
  ProviderHandler.configure_search(config)
  ProvisionerHandler.run_chef(config)
  ProviderHandler.configure_hosts(config)
  ProviderHandler.vm_clean_up(config)
end
