require_relative '../core/handlers/system_handler'
require_relative '../core/handlers/validation_handler'
require_relative '../core/handlers/hypervisor_handler'

SystemHandler.clear_screen
ValidationHandler.validate

Vagrant.configure('2') do |config|
	config.ssh.insert_key = false
	config.ssh.forward_agent = true
	config.vm.box = 'bento/ubuntu-18.04'
	config.vm.define 'Kukla-Machine' do |machine|
		HypervisorHandler.configure_network(machine)
	end

	config.vm.provider Hypervisor.value do |machine|
		HypervisorHandler.customize_vm(machine)
	end

	HypervisorHandler.copy_items(config)
	HypervisorHandler.configure_hosts(config)
	HypervisorHandler.configure_search(config)

	config.vm.provision 'shell',
	                    name: 'Installing pre-build packages',
	                    path: 'scripts/install_prebuild_packages.sh'

	config.vm.provision 'chef_zero' do |chef|
		chef.version = '16.13.16'
		chef.nodes_path = 'nodes'
		chef.environments_path = 'environments'
		chef.roles_path = 'roles'
		chef.cookbooks_path = 'cookbooks'
		chef.environment = 'vm'
		chef.add_role 'main'
		chef.arguments = '--chef-license accept'
	end
end
